### ISSUE TITLE
'column_categorical_with_identity()' requires default argument?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tfestimators#85] opened 2017-08-31 01:51 UTC
E.g. I'm seeing:

```R
> cols <- feature_columns(
+   column_numeric("profit"),
+   column_categorical_with_identity("profession", num_buckets = 5L)
+ )
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: default_value [] not in range [0, 5), column_name profession
```

The function signature:

```R
> column_categorical_with_identity
function(..., num_buckets, default_value = NULL) { ... }
```

@terrytangyuan should `default_value` be using e.g. `0` as the default value here?

**Comment by terrytangyuan** [comment] 2017-08-31 02:30
Which dataset is this?

**Comment by kevinushey** [comment] 2017-08-31 02:33
There is no data set associated. Just attempting to construct the feature column is failing.

**Comment by terrytangyuan** [comment] 2017-08-31 02:35
Oh I see your point now. I think in this case switching to 0 is indeed more user-friendly.

**Comment by terrytangyuan** [comment] 2017-08-31 02:44
The issue is right now our feature columns wrapper is associated with the dataset. For the Python API, it's more lazily evaluated, e.g. this works in Python:
```
from tensorflow.python.feature_column import feature_column_lib as fc
column = fc.categorical_column_with_identity('profession', num_buckets=5)
```

**Comment by terrytangyuan** [comment] 2017-08-31 03:13
Should be fixed in head.

**Closed by terrytangyuan** 2017-08-31 03:13 UTC
